CREATE TABLE IF NOT EXISTS Books(
    bookID INTEGER NOT NULL PRIMARY KEY AUTOINCREMENT,
    title TEXT NOT NULL DEFAULT 'Unknown' COLLATE NOCASE,
    isbn TEXT DEFAULT '' COLLATE NOCASE,
    createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS BookFiles(
    bookId INTEGER NOT NULL,
    filePath TEXT,
    fileType TEXT,
    createDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    modifiedDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(bookId) REFERENCES Books(bookId),
    UNIQUE(bookId, filePath, fileType)
);

CREATE TABLE IF NOT EXISTS Authors(
    author TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS BookAuthors(
    bookId INTEGER NOT NULL,
    author TEXT NOT NULL,
    PRIMARY KEY(bookId, author),
    FOREIGN KEY (bookId) REFERENCES Books(bookId),
    FOREIGN KEY (author) REFERENCES Authors(author)
);

CREATE TABLE IF NOT EXISTS Tags(
    tag TEXT NOT NULL PRIMARY KEY
);

CREATE TABLE IF NOT EXISTS BookTags(
    bookId INTEGER NOT NULL,
    tag TEXT NOT NULL,
    PRIMARY KEY(bookId, tag),
    FOREIGN KEY (bookId) REFERENCES Books(bookId),
    FOREIGN KEY (tag) REFERENCES Tags(tag)
);
